import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <>
      <nav className="navbar flex flex-row items-center justify-between px-16 py-4">
        <div className="nav-left">
          logo
        </div>
        <div className="nav-right">
          <ul className="flex flex-row items-center justify-between">
            <li className="mx-3"><Link href="./charting"> Charts</Link></li>
            <li className="mx-3"><Link href="./position">Position</Link></li>
            <li className="ml-3"><Link href="./performance">History</Link></li>
            <li className="ml-3"><Link href="./Order">Order</Link></li>
            <li className="ml-3"><Link href="../home">User</Link></li>
          </ul>
        </div>
      </nav>
      {children}
    </>
    // <html lang="en">
    //   <body className={inter.className}>
    //       <>
    //         <nav className="flex flex-row items-center justify-between px-16 py-4 bg-slate-800">
    //           <div className="nav-left">
    //             logo
    //           </div>
    //           <div className="nav-right">
    //             <ul className="flex flex-row items-center justify-between">
    //               <li className="mx-3"><Link href="./charting"> Charts</Link></li>
    //               <li className="mx-3"><Link href="./position">Position</Link></li>
    //               <li className="ml-3"><Link href="./performance">History</Link></li>
    //               <li className="ml-3"><Link href="./Order">Order</Link></li>
    //               <li className="ml-3"><Link href="../home">User</Link></li>
    //             </ul>
    //           </div>
    //         </nav>
    //         {children}
    //       </>
    //   </body>
    // </html>
  );
}
